### ISSUE TITLE
example 的bat，如果连续顺序读取多个设备的数据，如何配置呢？

### ISSUE THREAD

**Issue by huanghe-1** [zengfr/easymodbus4j#10]
比如有10个设备，设备id是1到10,命令貌似不支持配置多少个设备

**Comment by zengfr** [comment]
拿到 channel可以和任意设备通信 见 quick start 4.1.

**Comment by kongdongshan** [comment]
明白了，是一个设备实例化一个ChannelSender ，各读各的，多个设备就实例化多个Sender.
