### ISSUE TITLE
精度问题。

### ISSUE THREAD

**Issue by zhengshengh** [zengfr/easymodbus4j#13]
你好，
为什么我们的精度只有小数点后面一位？
其他诸如施耐德PSO、西门子WinCC都至少有3位小数。
请问有没有什么办法增加精度呢?
![image](https://user-images.githubusercontent.com/6629532/106694138-ec9ba580-6612-11eb-8679-dd43b69ee615.png)

**Comment by zengfr** [comment]
看不到图片 找我联系方式 私发我 谢谢啦
