### ISSUE TITLE
ChannelSender.unitId在同时连接两个modusSlave的时候会导致unitId相同

### ISSUE THREAD

**Issue by TomGitHome** [zengfr/easymodbus4j#16]
![image](https://user-images.githubusercontent.com/44091477/216309267-ad730723-7b64-4d72-a6fb-57cac287ff87.png)

使用全局变量在同时启动连接两个modusSlave的时候，会出现ID相同的
![image](https://user-images.githubusercontent.com/44091477/216309446-1e23e95d-c90c-44c3-8348-c7141f0786e0.png)
![image](https://user-images.githubusercontent.com/44091477/216309508-07ea24b6-0fb8-425a-89b2-e599ad8ac177.png)

**Comment by zengfr** [comment]
> ![image](https://user-images.githubusercontent.com/44091477/216309267-ad730723-7b64-4d72-a6fb-57cac287ff87.png)
> 
> 使用全局变量在同时启动连接两个modusSlave的时候，会出现ID相同的 ![image](https://user-images.githubusercontent.com/44091477/216309446-1e23e95d-c90c-44c3-8348-c7141f0786e0.png) ![image](https://user-images.githubusercontent.com/44091477/216309508-07ea24b6-0fb8-425a-89b2-e599ad8ac177.png)

var sender=new ChannelSender(XX,XX);
