### ISSUE TITLE
请问有rtu on tcp/ip同步请求的例子吗

### ISSUE THREAD

**Issue by jiaoyilun** [zengfr/easymodbus4j#3]
请问有rtu on tcp/ip同步请求的例子吗

**Comment by zengfr** [comment]
TCP服务器master,TCP客户端slave,TCP服务器slave,TCP客户端master
RTU服务器master,RTU客户端slave,RTU服务器slave,RTU客户端master
查看8种模式  resource下 bat 文件。
maven package打包后 解压运行对应的bat文件。

https://github.com/zengfr/easymodbus4j/tree/master/easymodbus4j-example/src/main/resources
