### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by yueye1** [zengfr/easymodbus4j#4]
启动会报一个错: Error: Unable to access jarfile easymodbus4j-example-0.0.1.jar

**Comment by zengfr** [comment]
麻烦邮件我下 然后微信联系 你截图或我看下

**Comment by yueye1** [comment]
你好,微信15155098401


这个是报错





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zengfr曾繁荣"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月7日(星期四) 下午5:12
收件人:&nbsp;"zengfr/easymodbus4j"<easymodbus4j@noreply.github.com&gt;;
抄送:&nbsp;"施伟峰"<1604948210@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zengfr/easymodbus4j] 启动报错 (#4)




麻烦邮件我下 然后微信联系 你截图或我看下
