### ISSUE TITLE
通过配置能够解耦掉这些东西吗

### ISSUE THREAD

**Issue by chinausers** [zengfr/easymodbus4j#6]
我想配置化掉这些东西只需要读取给定的文件就能生成从或主

**Comment by zengfr** [comment]
已经配制化了哦 
查看resource下bat执行文件  参数type不同模式
switch (cfg.type)
https://github.com/zengfr/easymodbus4j/blob/master/easymodbus4j-example/src/main/java/com/github/zengfr/easymodbus4j/example/ModbusConsoleApp.java
