### ISSUE TITLE
transactionIdentifierOffset 参数是什么意义，貌似随便改也不影响

### ISSUE THREAD

**Issue by kongdongshan** [zengfr/easymodbus4j#8]
start8-Client4RtuMaster.bat
@echo off
rem type,host,port,unit_IDENTIFIER,transactionIdentifierOffset,showDebugLog,idleTimeout,autoSend,sleep,heartbeat,ignoreLengthThreshold,udpPort
java -jar easymodbus4j-example-0.0.5.jar 8,127.0.0.1,502,1,0,T,0,T,12000,heartbeat,0,54321
pause
@echo on

transactionIdentifierOffset 随便改个数，结果没有影响，是必要的吗

**Comment by zengfr** [comment]
默认设置0  特殊情况下设置1。

**Comment by kongdongshan** [comment]
1和0分别代表什么意思啊
